production:
    adapter: mysql
    username: root
    password: root
    socket: /var/run/mysqld/mysqld.sock
    database: illyriad_production

development:
  adapter: mysql
  username: root
  password: root
  socket: /tmp/mysql.sock
  database: illyriad_development
  
test:
  adapter: mysql
  username: root
  password: root
  socket: /tmp/mysql.sock
  database: illyriad_test