development:
  adapter: mysql
  username: root
  password: root
  socket: /tmp/mysql.sock
  database: illyriad_development
  
test:
  adapter: mysql
  username: root
  password: root
  socket: /tmp/mysql.sock
  database: illyriad_test